/*
02_cleaning_missing_flags.sql

Creates SQL cleaning flags and missing-value flags for the application table.
This maps to Step 3 cleaning logic.
*/

CREATE OR REPLACE VIEW v02_application_cleaning_flags AS
SELECT
    a.*,

    /* Special-value flags */
    CASE WHEN CODE_GENDER = 'XNA' THEN 1 ELSE 0 END AS CODE_GENDER_UNKNOWN_FLAG,
    CASE WHEN DAYS_EMPLOYED = 365243 THEN 1 ELSE 0 END AS DAYS_EMPLOYED_ANOM_FLAG,
    CASE WHEN DAYS_EMPLOYED = 365243 THEN NULL ELSE DAYS_EMPLOYED END AS DAYS_EMPLOYED_CLEAN,

    /* External-source missing flags */
    CASE WHEN EXT_SOURCE_1 IS NULL THEN 1 ELSE 0 END AS EXT_SOURCE_1_MISSING_FLAG,
    CASE WHEN EXT_SOURCE_2 IS NULL THEN 1 ELSE 0 END AS EXT_SOURCE_2_MISSING_FLAG,
    CASE WHEN EXT_SOURCE_3 IS NULL THEN 1 ELSE 0 END AS EXT_SOURCE_3_MISSING_FLAG,
    (
        CASE WHEN EXT_SOURCE_1 IS NULL THEN 1 ELSE 0 END
      + CASE WHEN EXT_SOURCE_2 IS NULL THEN 1 ELSE 0 END
      + CASE WHEN EXT_SOURCE_3 IS NULL THEN 1 ELSE 0 END
    ) AS EXT_SOURCE_MISSING_COUNT,

    /* Asset / housing missing flags */
    CASE WHEN OWN_CAR_AGE IS NULL THEN 1 ELSE 0 END AS APP_OWN_CAR_AGE_MISSING_FLAG,
    (
        CASE WHEN APARTMENTS_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN BASEMENTAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN YEARS_BEGINEXPLUATATION_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN YEARS_BUILD_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN COMMONAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN ELEVATORS_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN ENTRANCES_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN FLOORSMAX_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN FLOORSMIN_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN LANDAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN LIVINGAPARTMENTS_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN LIVINGAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN NONLIVINGAPARTMENTS_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN NONLIVINGAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN FONDKAPREMONT_MODE IS NULL THEN 1 ELSE 0 END
      + CASE WHEN HOUSETYPE_MODE IS NULL THEN 1 ELSE 0 END
      + CASE WHEN WALLSMATERIAL_MODE IS NULL THEN 1 ELSE 0 END
      + CASE WHEN EMERGENCYSTATE_MODE IS NULL THEN 1 ELSE 0 END
    ) AS APP_PROPERTY_MISSING_COUNT,
    (
        CASE WHEN APARTMENTS_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN BASEMENTAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN YEARS_BEGINEXPLUATATION_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN YEARS_BUILD_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN COMMONAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN ELEVATORS_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN ENTRANCES_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN FLOORSMAX_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN FLOORSMIN_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN LANDAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN LIVINGAPARTMENTS_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN LIVINGAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN NONLIVINGAPARTMENTS_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN NONLIVINGAREA_AVG IS NULL THEN 1 ELSE 0 END
      + CASE WHEN FONDKAPREMONT_MODE IS NULL THEN 1 ELSE 0 END
      + CASE WHEN HOUSETYPE_MODE IS NULL THEN 1 ELSE 0 END
      + CASE WHEN WALLSMATERIAL_MODE IS NULL THEN 1 ELSE 0 END
      + CASE WHEN EMERGENCYSTATE_MODE IS NULL THEN 1 ELSE 0 END
    ) * 1.0 / 18 AS APP_PROPERTY_MISSING_RATIO,
    CASE
        WHEN (
            CASE WHEN APARTMENTS_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN BASEMENTAREA_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN YEARS_BEGINEXPLUATATION_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN YEARS_BUILD_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN COMMONAREA_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN ELEVATORS_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN ENTRANCES_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN FLOORSMAX_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN FLOORSMIN_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN LANDAREA_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN LIVINGAPARTMENTS_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN LIVINGAREA_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN NONLIVINGAPARTMENTS_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN NONLIVINGAREA_AVG IS NULL THEN 1 ELSE 0 END
          + CASE WHEN FONDKAPREMONT_MODE IS NULL THEN 1 ELSE 0 END
          + CASE WHEN HOUSETYPE_MODE IS NULL THEN 1 ELSE 0 END
          + CASE WHEN WALLSMATERIAL_MODE IS NULL THEN 1 ELSE 0 END
          + CASE WHEN EMERGENCYSTATE_MODE IS NULL THEN 1 ELSE 0 END
        ) > 0 THEN 1 ELSE 0
    END AS APP_PROPERTY_ANY_MISSING_FLAG
FROM v01_application_base a;

