/*
03_feature_engineering_application.sql

Creates application-level engineered features and ratios.
This maps to Step 3 feature engineering logic.
*/

CREATE OR REPLACE VIEW v03_application_features AS
SELECT
    a.*,
    -DAYS_BIRTH / 365.25 AS APP_AGE_YEARS,
    -DAYS_EMPLOYED_CLEAN / 365.25 AS APP_EMPLOYED_YEARS,
    -DAYS_REGISTRATION / 365.25 AS APP_REGISTRATION_YEARS,
    -DAYS_ID_PUBLISH / 365.25 AS APP_ID_PUBLISH_YEARS,
    -DAYS_LAST_PHONE_CHANGE / 365.25 AS APP_LAST_PHONE_CHANGE_YEARS,

    AMT_CREDIT / NULLIF(AMT_INCOME_TOTAL, 0) AS APP_CREDIT_INCOME_RATIO,
    AMT_ANNUITY / NULLIF(AMT_INCOME_TOTAL, 0) AS APP_ANNUITY_INCOME_RATIO,
    AMT_GOODS_PRICE / NULLIF(AMT_CREDIT, 0) AS APP_GOODS_CREDIT_RATIO,
    AMT_INCOME_TOTAL / NULLIF(CNT_FAM_MEMBERS, 0) AS APP_INCOME_PER_PERSON,
    CNT_CHILDREN * 1.0 / NULLIF(CNT_FAM_MEMBERS, 0) AS APP_CHILDREN_RATIO,

    /* Combined external score features for dashboard/ML interpretation */
    (COALESCE(EXT_SOURCE_1, 0) + COALESCE(EXT_SOURCE_2, 0) + COALESCE(EXT_SOURCE_3, 0))
        / NULLIF(
            CASE WHEN EXT_SOURCE_1 IS NULL THEN 0 ELSE 1 END
          + CASE WHEN EXT_SOURCE_2 IS NULL THEN 0 ELSE 1 END
          + CASE WHEN EXT_SOURCE_3 IS NULL THEN 0 ELSE 1 END,
          0
        ) AS APP_EXT_SOURCE_MEAN_AVAILABLE
FROM v02_application_cleaning_flags a;

