/*
04_aggregate_bureau_and_bureau_balance.sql

Aggregates bureau and bureau_balance histories to customer level.
This maps to Step 5 historical aggregation logic.
*/

CREATE OR REPLACE VIEW v04_bureau_agg AS
WITH bureau_prepared AS (
    SELECT
        b.*,
        CASE WHEN CREDIT_ACTIVE = 'Active' THEN 1 ELSE 0 END AS BUREAU_IS_ACTIVE,
        CASE WHEN CREDIT_ACTIVE = 'Closed' THEN 1 ELSE 0 END AS BUREAU_IS_CLOSED,
        CASE WHEN CREDIT_ACTIVE = 'Bad debt' THEN 1 ELSE 0 END AS BUREAU_IS_BAD_DEBT,
        CASE
            WHEN COALESCE(CREDIT_DAY_OVERDUE, 0) > 0
              OR COALESCE(AMT_CREDIT_SUM_OVERDUE, 0) > 0
            THEN 1 ELSE 0
        END AS BUREAU_HAS_OVERDUE,
        CASE WHEN DAYS_CREDIT_ENDDATE > 0 THEN 1 ELSE 0 END AS BUREAU_ENDDATE_FUTURE_FLAG,
        AMT_CREDIT_SUM_DEBT / NULLIF(AMT_CREDIT_SUM, 0) AS BUREAU_DEBT_CREDIT_RATIO_RAW
    FROM bureau b
)
SELECT
    SK_ID_CURR,
    COUNT(SK_ID_BUREAU) AS BUREAU_LOAN_COUNT,
    SUM(BUREAU_IS_ACTIVE) AS BUREAU_ACTIVE_COUNT,
    SUM(BUREAU_IS_CLOSED) AS BUREAU_CLOSED_COUNT,
    SUM(BUREAU_IS_BAD_DEBT) AS BUREAU_BAD_DEBT_COUNT,
    SUM(BUREAU_HAS_OVERDUE) AS BUREAU_OVERDUE_LOAN_COUNT,
    MAX(CREDIT_DAY_OVERDUE) AS BUREAU_CREDIT_DAY_OVERDUE_MAX,
    AVG(CREDIT_DAY_OVERDUE) AS BUREAU_CREDIT_DAY_OVERDUE_MEAN,
    MAX(DAYS_CREDIT) AS BUREAU_DAYS_CREDIT_RECENT,
    MIN(DAYS_CREDIT) AS BUREAU_DAYS_CREDIT_OLDEST,
    SUM(BUREAU_ENDDATE_FUTURE_FLAG) AS BUREAU_ENDDATE_FUTURE_COUNT,
    SUM(AMT_CREDIT_SUM) AS BUREAU_AMT_CREDIT_SUM_SUM,
    AVG(AMT_CREDIT_SUM) AS BUREAU_AMT_CREDIT_SUM_MEAN,
    MAX(AMT_CREDIT_SUM) AS BUREAU_AMT_CREDIT_SUM_MAX,
    SUM(AMT_CREDIT_SUM_DEBT) AS BUREAU_AMT_DEBT_SUM,
    AVG(AMT_CREDIT_SUM_DEBT) AS BUREAU_AMT_DEBT_MEAN,
    SUM(AMT_CREDIT_SUM_OVERDUE) AS BUREAU_AMT_OVERDUE_SUM,
    MAX(AMT_CREDIT_SUM_OVERDUE) AS BUREAU_AMT_OVERDUE_MAX,
    SUM(CNT_CREDIT_PROLONG) AS BUREAU_CREDIT_PROLONG_SUM,
    AVG(BUREAU_DEBT_CREDIT_RATIO_RAW) AS BUREAU_DEBT_CREDIT_RATIO_MEAN,
    MAX(BUREAU_DEBT_CREDIT_RATIO_RAW) AS BUREAU_DEBT_CREDIT_RATIO_MAX,
    SUM(BUREAU_IS_ACTIVE) * 1.0 / NULLIF(COUNT(SK_ID_BUREAU), 0) AS BUREAU_ACTIVE_RATE,
    SUM(BUREAU_HAS_OVERDUE) * 1.0 / NULLIF(COUNT(SK_ID_BUREAU), 0) AS BUREAU_OVERDUE_RATE,
    SUM(AMT_CREDIT_SUM_DEBT) / NULLIF(SUM(AMT_CREDIT_SUM), 0) AS BUREAU_DEBT_TO_CREDIT_SUM_RATIO
FROM bureau_prepared
GROUP BY SK_ID_CURR;

CREATE OR REPLACE VIEW v04_bureau_balance_agg AS
WITH bureau_balance_prepared AS (
    SELECT
        b.SK_ID_CURR,
        bb.MONTHS_BALANCE,
        CASE WHEN bb.STATUS IN ('1', '2', '3', '4', '5') THEN 1 ELSE 0 END AS BB_OVERDUE_FLAG,
        CASE WHEN bb.STATUS = '5' THEN 1 ELSE 0 END AS BB_BAD_STATUS_FLAG,
        CASE
            WHEN bb.STATUS IN ('1', '2', '3', '4', '5') THEN CAST(bb.STATUS AS INTEGER)
            ELSE 0
        END AS BB_STATUS_NUM
    FROM bureau_balance bb
    INNER JOIN bureau b
        ON bb.SK_ID_BUREAU = b.SK_ID_BUREAU
)
SELECT
    SK_ID_CURR,
    COUNT(MONTHS_BALANCE) AS BB_MONTH_COUNT,
    MIN(MONTHS_BALANCE) AS BB_MONTHS_BALANCE_MIN,
    MAX(MONTHS_BALANCE) AS BB_MONTHS_BALANCE_MAX,
    SUM(BB_OVERDUE_FLAG) AS BB_OVERDUE_MONTH_COUNT,
    SUM(BB_BAD_STATUS_FLAG) AS BB_BAD_STATUS_MONTH_COUNT,
    MAX(BB_STATUS_NUM) AS BB_MAX_STATUS,
    SUM(BB_OVERDUE_FLAG) * 1.0 / NULLIF(COUNT(MONTHS_BALANCE), 0) AS BB_OVERDUE_MONTH_RATE,
    SUM(BB_BAD_STATUS_FLAG) * 1.0 / NULLIF(COUNT(MONTHS_BALANCE), 0) AS BB_BAD_STATUS_MONTH_RATE
FROM bureau_balance_prepared
GROUP BY SK_ID_CURR;

