/*
05_aggregate_previous_pos_installments_credit_card.sql

Aggregates previous applications, POS/CASH, installment payments, and credit
card monthly histories to customer level.
*/

CREATE OR REPLACE VIEW v05_previous_application_agg AS
WITH previous_prepared AS (
    SELECT
        p.*,
        CASE WHEN NAME_CONTRACT_STATUS = 'Approved' THEN 1 ELSE 0 END AS PREV_APPROVED_FLAG,
        CASE WHEN NAME_CONTRACT_STATUS = 'Refused' THEN 1 ELSE 0 END AS PREV_REFUSED_FLAG,
        CASE WHEN NAME_CONTRACT_STATUS = 'Canceled' THEN 1 ELSE 0 END AS PREV_CANCELED_FLAG,
        CASE WHEN NAME_CONTRACT_STATUS = 'Unused offer' THEN 1 ELSE 0 END AS PREV_UNUSED_OFFER_FLAG,
        CASE WHEN COALESCE(AMT_APPLICATION, 0) = 0 THEN 1 ELSE 0 END AS PREV_ZERO_APPLICATION_FLAG,
        CASE WHEN COALESCE(AMT_CREDIT, 0) = 0 THEN 1 ELSE 0 END AS PREV_ZERO_CREDIT_FLAG,
        AMT_CREDIT / NULLIF(AMT_APPLICATION, 0) AS PREV_CREDIT_APPLICATION_RATIO
    FROM previous_application p
)
SELECT
    SK_ID_CURR,
    COUNT(SK_ID_PREV) AS PREV_APP_COUNT,
    SUM(PREV_APPROVED_FLAG) AS PREV_APPROVED_COUNT,
    SUM(PREV_REFUSED_FLAG) AS PREV_REFUSED_COUNT,
    SUM(PREV_CANCELED_FLAG) AS PREV_CANCELED_COUNT,
    SUM(PREV_UNUSED_OFFER_FLAG) AS PREV_UNUSED_OFFER_COUNT,
    SUM(PREV_ZERO_APPLICATION_FLAG) AS PREV_ZERO_APPLICATION_COUNT,
    SUM(PREV_ZERO_CREDIT_FLAG) AS PREV_ZERO_CREDIT_COUNT,
    SUM(AMT_APPLICATION) AS PREV_AMT_APPLICATION_SUM,
    AVG(AMT_APPLICATION) AS PREV_AMT_APPLICATION_MEAN,
    MAX(AMT_APPLICATION) AS PREV_AMT_APPLICATION_MAX,
    SUM(AMT_CREDIT) AS PREV_AMT_CREDIT_SUM,
    AVG(AMT_CREDIT) AS PREV_AMT_CREDIT_MEAN,
    MAX(AMT_CREDIT) AS PREV_AMT_CREDIT_MAX,
    AVG(AMT_ANNUITY) AS PREV_AMT_ANNUITY_MEAN,
    MAX(DAYS_DECISION) AS PREV_DAYS_DECISION_RECENT,
    MIN(DAYS_DECISION) AS PREV_DAYS_DECISION_OLDEST,
    AVG(DAYS_DECISION) AS PREV_DAYS_DECISION_MEAN,
    AVG(PREV_CREDIT_APPLICATION_RATIO) AS PREV_CREDIT_APPLICATION_RATIO_MEAN,
    SUM(PREV_APPROVED_FLAG) * 1.0 / NULLIF(COUNT(SK_ID_PREV), 0) AS PREV_APPROVAL_RATE,
    SUM(PREV_REFUSED_FLAG) * 1.0 / NULLIF(COUNT(SK_ID_PREV), 0) AS PREV_REFUSAL_RATE,
    SUM(PREV_CANCELED_FLAG) * 1.0 / NULLIF(COUNT(SK_ID_PREV), 0) AS PREV_CANCELED_RATE
FROM previous_prepared
GROUP BY SK_ID_CURR;

CREATE OR REPLACE VIEW v05_pos_cash_agg AS
WITH pos_prepared AS (
    SELECT
        p.*,
        CASE WHEN NAME_CONTRACT_STATUS = 'Active' THEN 1 ELSE 0 END AS POS_ACTIVE_FLAG,
        CASE WHEN NAME_CONTRACT_STATUS = 'Completed' THEN 1 ELSE 0 END AS POS_COMPLETED_FLAG,
        CASE WHEN NAME_CONTRACT_STATUS = 'Demand' THEN 1 ELSE 0 END AS POS_DEMAND_FLAG,
        CASE WHEN COALESCE(SK_DPD, 0) > 0 THEN 1 ELSE 0 END AS POS_DPD_FLAG,
        CASE WHEN COALESCE(SK_DPD_DEF, 0) > 0 THEN 1 ELSE 0 END AS POS_DPD_DEF_FLAG,
        CASE WHEN CNT_INSTALMENT_FUTURE > CNT_INSTALMENT THEN 1 ELSE 0 END AS POS_FUTURE_GT_TOTAL_FLAG
    FROM POS_CASH_balance p
)
SELECT
    SK_ID_CURR,
    COUNT(MONTHS_BALANCE) AS POS_MONTH_COUNT,
    COUNT(DISTINCT SK_ID_PREV) AS POS_PREV_COUNT,
    MAX(MONTHS_BALANCE) AS POS_MONTHS_BALANCE_RECENT,
    MIN(MONTHS_BALANCE) AS POS_MONTHS_BALANCE_OLDEST,
    SUM(POS_ACTIVE_FLAG) AS POS_ACTIVE_MONTH_COUNT,
    SUM(POS_COMPLETED_FLAG) AS POS_COMPLETED_MONTH_COUNT,
    SUM(POS_DEMAND_FLAG) AS POS_DEMAND_MONTH_COUNT,
    SUM(POS_DPD_FLAG) AS POS_DPD_MONTH_COUNT,
    SUM(POS_DPD_DEF_FLAG) AS POS_DPD_DEF_MONTH_COUNT,
    MAX(SK_DPD) AS POS_SK_DPD_MAX,
    AVG(SK_DPD) AS POS_SK_DPD_MEAN,
    MAX(SK_DPD_DEF) AS POS_SK_DPD_DEF_MAX,
    AVG(SK_DPD_DEF) AS POS_SK_DPD_DEF_MEAN,
    AVG(CNT_INSTALMENT) AS POS_CNT_INSTALMENT_MEAN,
    MAX(CNT_INSTALMENT) AS POS_CNT_INSTALMENT_MAX,
    AVG(CNT_INSTALMENT_FUTURE) AS POS_CNT_INSTALMENT_FUTURE_MEAN,
    MIN(CNT_INSTALMENT_FUTURE) AS POS_CNT_INSTALMENT_FUTURE_MIN,
    SUM(POS_FUTURE_GT_TOTAL_FLAG) AS POS_FUTURE_GT_TOTAL_COUNT,
    SUM(POS_DPD_FLAG) * 1.0 / NULLIF(COUNT(MONTHS_BALANCE), 0) AS POS_DPD_MONTH_RATE,
    SUM(POS_DPD_DEF_FLAG) * 1.0 / NULLIF(COUNT(MONTHS_BALANCE), 0) AS POS_DPD_DEF_MONTH_RATE
FROM pos_prepared
GROUP BY SK_ID_CURR;

CREATE OR REPLACE VIEW v05_installments_agg AS
WITH installments_prepared AS (
    SELECT
        i.*,
        DAYS_ENTRY_PAYMENT - DAYS_INSTALMENT AS INST_DAYS_LATE,
        CASE WHEN DAYS_ENTRY_PAYMENT - DAYS_INSTALMENT > 0 THEN DAYS_ENTRY_PAYMENT - DAYS_INSTALMENT ELSE 0 END AS INST_DAYS_LATE_POSITIVE,
        CASE WHEN DAYS_INSTALMENT - DAYS_ENTRY_PAYMENT > 0 THEN DAYS_INSTALMENT - DAYS_ENTRY_PAYMENT ELSE 0 END AS INST_DAYS_EARLY_POSITIVE,
        CASE WHEN DAYS_ENTRY_PAYMENT - DAYS_INSTALMENT > 0 THEN 1 ELSE 0 END AS INST_LATE_FLAG,
        CASE WHEN AMT_PAYMENT < AMT_INSTALMENT THEN 1 ELSE 0 END AS INST_UNDERPAYMENT_FLAG,
        CASE WHEN DAYS_ENTRY_PAYMENT IS NULL THEN 1 ELSE 0 END AS INST_PAYMENT_MISSING_FLAG,
        AMT_PAYMENT / NULLIF(AMT_INSTALMENT, 0) AS INST_PAYMENT_RATIO
    FROM installments_payments i
)
SELECT
    SK_ID_CURR,
    COUNT(NUM_INSTALMENT_NUMBER) AS INST_PAYMENT_COUNT,
    COUNT(DISTINCT SK_ID_PREV) AS INST_PREV_COUNT,
    SUM(INST_LATE_FLAG) AS INST_LATE_PAYMENT_COUNT,
    SUM(INST_UNDERPAYMENT_FLAG) AS INST_UNDERPAYMENT_COUNT,
    SUM(INST_PAYMENT_MISSING_FLAG) AS INST_PAYMENT_MISSING_COUNT,
    SUM(INST_DAYS_LATE_POSITIVE) AS INST_DAYS_LATE_POSITIVE_SUM,
    AVG(INST_DAYS_LATE_POSITIVE) AS INST_DAYS_LATE_POSITIVE_MEAN,
    MAX(INST_DAYS_LATE_POSITIVE) AS INST_DAYS_LATE_POSITIVE_MAX,
    AVG(INST_DAYS_EARLY_POSITIVE) AS INST_DAYS_EARLY_POSITIVE_MEAN,
    SUM(AMT_INSTALMENT) AS INST_AMT_INSTALMENT_SUM,
    AVG(AMT_INSTALMENT) AS INST_AMT_INSTALMENT_MEAN,
    SUM(AMT_PAYMENT) AS INST_AMT_PAYMENT_SUM,
    AVG(AMT_PAYMENT) AS INST_AMT_PAYMENT_MEAN,
    AVG(INST_PAYMENT_RATIO) AS INST_PAYMENT_RATIO_MEAN,
    MIN(INST_PAYMENT_RATIO) AS INST_PAYMENT_RATIO_MIN,
    SUM(INST_LATE_FLAG) * 1.0 / NULLIF(COUNT(NUM_INSTALMENT_NUMBER), 0) AS INST_LATE_PAYMENT_RATE,
    SUM(INST_UNDERPAYMENT_FLAG) * 1.0 / NULLIF(COUNT(NUM_INSTALMENT_NUMBER), 0) AS INST_UNDERPAYMENT_RATE,
    SUM(AMT_PAYMENT) / NULLIF(SUM(AMT_INSTALMENT), 0) AS INST_TOTAL_PAYMENT_RATIO
FROM installments_prepared
GROUP BY SK_ID_CURR;

CREATE OR REPLACE VIEW v05_credit_card_agg AS
WITH credit_card_prepared AS (
    SELECT
        c.*,
        CASE WHEN COALESCE(AMT_CREDIT_LIMIT_ACTUAL, 0) = 0 THEN 1 ELSE 0 END AS CC_ZERO_LIMIT_FLAG,
        AMT_BALANCE / NULLIF(AMT_CREDIT_LIMIT_ACTUAL, 0) AS CC_UTILIZATION,
        CASE WHEN AMT_BALANCE / NULLIF(AMT_CREDIT_LIMIT_ACTUAL, 0) > 1 THEN 1 ELSE 0 END AS CC_UTILIZATION_GT_1_FLAG,
        CASE WHEN NAME_CONTRACT_STATUS = 'Active' THEN 1 ELSE 0 END AS CC_ACTIVE_FLAG,
        CASE WHEN NAME_CONTRACT_STATUS = 'Completed' THEN 1 ELSE 0 END AS CC_COMPLETED_FLAG,
        CASE WHEN COALESCE(SK_DPD, 0) > 0 THEN 1 ELSE 0 END AS CC_DPD_FLAG,
        CASE WHEN COALESCE(SK_DPD_DEF, 0) > 0 THEN 1 ELSE 0 END AS CC_DPD_DEF_FLAG,
        CASE WHEN AMT_BALANCE < 0 THEN 1 ELSE 0 END AS CC_NEGATIVE_BALANCE_FLAG
    FROM credit_card_balance c
)
SELECT
    SK_ID_CURR,
    COUNT(MONTHS_BALANCE) AS CC_MONTH_COUNT,
    COUNT(DISTINCT SK_ID_PREV) AS CC_PREV_COUNT,
    MAX(MONTHS_BALANCE) AS CC_MONTHS_BALANCE_RECENT,
    MIN(MONTHS_BALANCE) AS CC_MONTHS_BALANCE_OLDEST,
    SUM(CC_ACTIVE_FLAG) AS CC_ACTIVE_MONTH_COUNT,
    SUM(CC_COMPLETED_FLAG) AS CC_COMPLETED_MONTH_COUNT,
    SUM(CC_ZERO_LIMIT_FLAG) AS CC_ZERO_LIMIT_MONTH_COUNT,
    SUM(CC_UTILIZATION_GT_1_FLAG) AS CC_UTILIZATION_GT_1_MONTH_COUNT,
    SUM(CC_NEGATIVE_BALANCE_FLAG) AS CC_NEGATIVE_BALANCE_MONTH_COUNT,
    AVG(AMT_BALANCE) AS CC_AMT_BALANCE_MEAN,
    MAX(AMT_BALANCE) AS CC_AMT_BALANCE_MAX,
    SUM(AMT_BALANCE) AS CC_AMT_BALANCE_SUM,
    AVG(AMT_CREDIT_LIMIT_ACTUAL) AS CC_CREDIT_LIMIT_MEAN,
    MAX(AMT_CREDIT_LIMIT_ACTUAL) AS CC_CREDIT_LIMIT_MAX,
    AVG(CC_UTILIZATION) AS CC_UTILIZATION_MEAN,
    MAX(CC_UTILIZATION) AS CC_UTILIZATION_MAX,
    SUM(AMT_DRAWINGS_CURRENT) AS CC_DRAWINGS_CURRENT_SUM,
    AVG(AMT_DRAWINGS_CURRENT) AS CC_DRAWINGS_CURRENT_MEAN,
    SUM(AMT_PAYMENT_CURRENT) AS CC_PAYMENT_CURRENT_SUM,
    AVG(AMT_PAYMENT_CURRENT) AS CC_PAYMENT_CURRENT_MEAN,
    AVG(AMT_TOTAL_RECEIVABLE) AS CC_TOTAL_RECEIVABLE_MEAN,
    MAX(AMT_TOTAL_RECEIVABLE) AS CC_TOTAL_RECEIVABLE_MAX,
    SUM(CC_DPD_FLAG) AS CC_DPD_MONTH_COUNT,
    SUM(CC_DPD_DEF_FLAG) AS CC_DPD_DEF_MONTH_COUNT,
    MAX(SK_DPD) AS CC_SK_DPD_MAX,
    AVG(SK_DPD) AS CC_SK_DPD_MEAN,
    MAX(SK_DPD_DEF) AS CC_SK_DPD_DEF_MAX,
    AVG(SK_DPD_DEF) AS CC_SK_DPD_DEF_MEAN,
    SUM(CC_ZERO_LIMIT_FLAG) * 1.0 / NULLIF(COUNT(MONTHS_BALANCE), 0) AS CC_ZERO_LIMIT_MONTH_RATE,
    SUM(CC_UTILIZATION_GT_1_FLAG) * 1.0 / NULLIF(COUNT(MONTHS_BALANCE), 0) AS CC_UTILIZATION_GT_1_MONTH_RATE,
    SUM(CC_DPD_FLAG) * 1.0 / NULLIF(COUNT(MONTHS_BALANCE), 0) AS CC_DPD_MONTH_RATE
FROM credit_card_prepared
GROUP BY SK_ID_CURR;

