/*
06_build_customer_master_table.sql

Builds the customer-level analytical master table through LEFT JOINs.
This maps to Step 5 final master table construction.
*/

CREATE OR REPLACE VIEW v06_customer_master_table AS
SELECT
    a.*,

    CASE WHEN b.SK_ID_CURR IS NOT NULL THEN 1 ELSE 0 END AS HAS_BUREAU_HISTORY,
    b.BUREAU_LOAN_COUNT,
    b.BUREAU_ACTIVE_COUNT,
    b.BUREAU_CLOSED_COUNT,
    b.BUREAU_BAD_DEBT_COUNT,
    b.BUREAU_OVERDUE_LOAN_COUNT,
    b.BUREAU_CREDIT_DAY_OVERDUE_MAX,
    b.BUREAU_ACTIVE_RATE,
    b.BUREAU_OVERDUE_RATE,
    b.BUREAU_DEBT_TO_CREDIT_SUM_RATIO,

    CASE WHEN bb.SK_ID_CURR IS NOT NULL THEN 1 ELSE 0 END AS HAS_BUREAU_BALANCE_HISTORY,
    bb.BB_MONTH_COUNT,
    bb.BB_OVERDUE_MONTH_COUNT,
    bb.BB_BAD_STATUS_MONTH_COUNT,
    bb.BB_MAX_STATUS,
    bb.BB_OVERDUE_MONTH_RATE,

    CASE WHEN p.SK_ID_CURR IS NOT NULL THEN 1 ELSE 0 END AS HAS_PREVIOUS_APPLICATION,
    p.PREV_APP_COUNT,
    p.PREV_APPROVED_COUNT,
    p.PREV_REFUSED_COUNT,
    p.PREV_REFUSAL_RATE,
    p.PREV_APPROVAL_RATE,
    p.PREV_AMT_APPLICATION_MEAN,
    p.PREV_AMT_CREDIT_MEAN,

    CASE WHEN pos.SK_ID_CURR IS NOT NULL THEN 1 ELSE 0 END AS HAS_POS_CASH_HISTORY,
    pos.POS_MONTH_COUNT,
    pos.POS_PREV_COUNT,
    pos.POS_DPD_MONTH_COUNT,
    pos.POS_DPD_MONTH_RATE,

    CASE WHEN inst.SK_ID_CURR IS NOT NULL THEN 1 ELSE 0 END AS HAS_INSTALLMENT_HISTORY,
    inst.INST_PAYMENT_COUNT,
    inst.INST_LATE_PAYMENT_COUNT,
    inst.INST_UNDERPAYMENT_COUNT,
    inst.INST_LATE_PAYMENT_RATE,
    inst.INST_UNDERPAYMENT_RATE,
    inst.INST_TOTAL_PAYMENT_RATIO,

    CASE WHEN cc.SK_ID_CURR IS NOT NULL THEN 1 ELSE 0 END AS HAS_CREDIT_CARD_HISTORY,
    cc.CC_MONTH_COUNT,
    cc.CC_PREV_COUNT,
    cc.CC_UTILIZATION_MEAN,
    cc.CC_UTILIZATION_MAX,
    cc.CC_UTILIZATION_GT_1_MONTH_COUNT,
    cc.CC_UTILIZATION_GT_1_MONTH_RATE,
    cc.CC_DPD_MONTH_RATE
FROM v03_application_features a
LEFT JOIN v04_bureau_agg b
    ON a.SK_ID_CURR = b.SK_ID_CURR
LEFT JOIN v04_bureau_balance_agg bb
    ON a.SK_ID_CURR = bb.SK_ID_CURR
LEFT JOIN v05_previous_application_agg p
    ON a.SK_ID_CURR = p.SK_ID_CURR
LEFT JOIN v05_pos_cash_agg pos
    ON a.SK_ID_CURR = pos.SK_ID_CURR
LEFT JOIN v05_installments_agg inst
    ON a.SK_ID_CURR = inst.SK_ID_CURR
LEFT JOIN v05_credit_card_agg cc
    ON a.SK_ID_CURR = cc.SK_ID_CURR;

